### ISSUE TITLE
mlWaitForTaskServer doesn't wait for active threads

### ISSUE THREAD

**Issue by grtjn** [rjrudin/ml-gradle#145] opened 2016-11-15 20:09 UTC
Related to #135. It returns as soon as the queue is empty, but ignores active threads..

**Comment by rjrudin** [comment] 2016-11-16 12:55
@grtjn Can you give an example of how to reproduce? I'm not sure what you mean by "active threads" either wrt the task server.

The testing I did involved code to what's below - just toss some requests on the task server that sleep for awhile, and make sure the Gradle task doesn't return until they've all finished.

for $i in 1 to 5
let $time := $i * 3000
return xdmp:spawn-function(function() { xdmp:sleep($time), xdmp:log("Done with " || $i) })

**Comment by grtjn** [comment] 2016-11-17 09:51
I think these spawns finish too quickly to notice. Here are some that wait for each other because of contention:

```xquery
for $i in 1 to 10
let $time := $i * 10 * 1000
return xdmp:spawn-function(
  function() {
    xdmp:document-insert("/test-lock.xml", <lock/>),
    xdmp:sleep($time),
    xdmp:log("Done with " || $i),
    "Done with " || $i
  },
  <options xmlns="xdmp:eval">
    <transaction-mode>update-auto-commit</transaction-mode>
    <result>true</result>
    <priority>higher</priority>
  </options>
)
```

What you then see in the admin ui is a discrepancy between (active) threads, and requests. Probably because it is still busy persisting:

<img width="914" alt="screen shot 2016-11-17 at 10 48 41 am" src="https://cloud.githubusercontent.com/assets/611397/20384368/d506794e-acb3-11e6-92d2-c73f0af87096.png">

**Comment by grtjn** [comment] 2016-11-17 09:56
To explain the screenshot a bit more: I started with 10 threads. First two have finished, but one of them is still flushing to disk. Hence Threads reads 9, but Requests (which is what your function is monitoring if I am correct) reads 8. In this case the delay between Requests and Threads is pretty small, so a little difficult to notice, but in a more elaborate system with read and write locks, a 3 node cluster with together 72 task server threads, and processing of many tasks (30k or more), the delay can be significantly larger..

It probably won't cause issues, but MarkLogic might not fully have settled down when the wait task returns. I have seen it take 30 sec to a minute on the cluster..

**Comment by rjrudin** [comment] 2016-11-17 19:46
I'm wondering what that 9th thread is. I just tested with your script, and the number of threads was always the same as the number of requests. And when I looked at /manage/v2/requests, the count was always the number of requests on the task server + 2 - the 1 running in qconsole (where I ran the script), and my request to /manage/v2/requests. 

I'm not sure what you mean about flushing to disk. From MarkLogic's perspective, the request and its transaction end at the same time, and the journal is updated. Data may not be flushed to disk for a long time. The request is still complete. 

I think the main question is - what constitutes the task server being "done"? I've always understood that to be - it's not processing any requests. That's what /manage/v2/requests and the Admin UI both display, so that seems to be a pretty authoritative answer. If there's a separate answer for it - and an API that returns that answer - I can call it, I just don't know what it is.

**Comment by grtjn** [comment] 2016-11-18 09:35
I noticed that cpu and mem usage only dropped after active threads being zero. I'd prefer the wait task to wait till the task server is completely done.

And yes, of course /manage/v2/requests tells you whether there are any requests or not, because that is what the endpoint is meant for.

I'm not sure why those threads linger around after completion of the request. I can only think of commit phase, which happens after completion of the request. To be sure, we'd have to ask engineering..

**Comment by rjrudin** [comment] 2016-12-05 20:41
@grtjn No clarification from anyone internally on this, right? I'm leaning towards closing this unless we get input on how to better answer the question of whether any task server threads are outstanding.

**Comment by rjrudin** [comment] 2016-12-20 18:21
Closing this, as no report yet on a better way of identifying tasks that are still ongoing. Will definitely support a better technique once one is identified.

**Closed by rjrudin** 2016-12-20 18:21 UTC
