### ISSUE TITLE
Loading Scheduled Tasks a second time fails  

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#39] opened 2015-09-10 15:50 UTC
This may be a Management API issues.  

Trying to load the following scheduled task a second time and I get a 500 error when it hits PUT /manage/v2/tasks/.  

If I remove the task-user property then it works.  

  {
   "task-enabled": false, 
   "task-path": "/ext/isearch/task/getDeltaObjects.xqy", 
   "task-root": "/", 
   "task-type": "weekly", 
   "task-period": 2, 
   "task-day": ["tuesday"], 
   "task-start-time": "12:00:00", 
   "task-database": "%%DATABASE%%", 
   "task-modules": "%%MODULES_DATABASE%%", 
   "task-user": "isearch-user"
}

**Comment by rjrudin** [comment] 2015-09-10 20:09
What error shows up in ErrorLog.txt? 

Can you reproduce it via a direct POST to 8002, bypassing ml-gradle? If the error occurs there, then it's outside the scope of ml-gradle.

**Comment by sastafford** [comment] 2015-09-10 20:16
2015-09-10 08:28:16.401 Info: Manage: MANAGE-INVALID (err:FOER0000): task-user

That's how I knew to remove task-user.  Originally the task-user was set to "nobody".  I changed to a different user that exists and it still failed.

**Comment by ndw** [comment] 2015-09-11 11:32
This is definitely a bug. After you've created a task, the only thing you can change is the status: enabled or disabled. The endpoint is supposed to accept all of the other properties provided that the values are unchanged. Apparently it's falling over on task-user; I'll see about getting that fixed in the (near term) future.

**Comment by rjrudin** [comment] 2015-09-11 12:10
Norm, is the expected behavior that only status can be changed, or is it that any of the properties can be changed?

At least for 8.0-3, I can make a small mod to the Command - https://github.com/rjrudin/ml-app-deployer/blob/master/src/main/java/com/rjrudin/marklogic/appdeployer/command/tasks/DeployScheduledTasksCommand.java - so that on an update, it strips out everything but the status field.

**Comment by ndw** [comment] 2015-09-11 12:15
I believe that after you've created a task, the only thing you can change
is whether or not it is enabled. To change anything else, you must delete
the task and insert a different one.

**Comment by sastafford** [comment] 2015-09-11 17:40
Until Norm gets a fix in, could we delete all scheduled tasks and add them back on every mlDeploy command?  We could also just manually create the tasks if this is too much of a hack.

**Comment by rjrudin** [comment] 2015-09-11 18:19
You can always make a custom task that deletes all scheduled tasks (one doesn't exist yet, but you could model it off DeployTasksTask and just tell the AppDeployer to do an undeploy instead of deploy), and then call that task before mlDeploy. Could make a "myDeploy" task that depends on "undeployTasks" and "mlDeploy" too.

**Comment by rjrudin** [comment] 2015-09-15 02:02
Scott - I can't reproduce this, and the test in ml-app-deployer - ManageScheduledTasksTest - shows a task being successfully updated with the same JSON that was used to create it. I've pasted the JSON below - I tried it with "admin" as the user and "Modules" as the modules-database, and it still works fine - i.e. the update is processed successfully.

{
   "task-enabled":true, 
   "task-path":"/path/to/query.xqy", 
   "task-root":"/", 
   "task-type":"weekly", 
   "task-period":2, 
   "task-day":["tuesday"], 
   "task-start-time":"12:00:00", 
   "task-database":"Documents", 
   "task-modules":"", 
   "task-user":"nobody"
}

**Comment by ndw** [comment] 2015-09-25 17:44
Any luck reproducing this, or can I close out my bugtrack bug for it?

**Comment by rjrudin** [comment] 2015-10-05 13:16
Scott, I'm going to close this out, I haven't been able to reproduce it.

**Closed by rjrudin** 2015-10-05 13:16 UTC

**Comment by rrumpf** [comment] 2017-05-16 17:27
I had precisely this same issue, but it turned out to be a permissions issue, not a gradle issue.

In order to create a scheduled task via mlDeployTasks, you needed one set of privileges. However, if the tasks already existed, running mlDeployTasks (with the same task configuration) would fail with the error: MANAGE-INVALID (err:FOER0000): task-user when run by the same (non-admin) user that created the task.

The way to fix this was to add the security role to the user interacting with MarkLogic via the REST API in this gradle task. Presumably, there are additional checks regarding roles and privileges when the task is deployed on top of itself.
